### PR TITLE
Code cleanup + Minor change

### PR DESCRIPTION
**Pull request by GreenMan36**
Seems like the default dropdowns weren't getting colored, you can find them in the Discord Experiments page and maybe 1 other place in the application.
I also removed duplicate/overwritten/useless value's in the theme files.

My commits are pretty descriptive of what I've done.

I wonder, what tools do you use during development?
My IDE before the changes:
image

My IDE after my changes;
image

I've taken a quick look around all the features I use, DM's, profiles, threads, settings, etc. But as far as I know, nothing broke.

### CODE REVIEW

**Comment by GreenMan36** [comment]
Holdup, I might've broken something 😅

**Comment by GreenMan36** [comment]
My IDE said b656e8fff4bc25f9a9c0e8ced8ebbfe1a2dee9fd was invalid but I guess my IDE has some outdated or wrong CSS info, MDN. My bad for not double checking when removing code.

Any clue what exactly (e08598eb36bcfbff168266f6a103b980c0b08a48)
```css
.contentColumn-1C7as6,
.customColumn-2n-oKU {
    -webkit-box-flex: 1;
    -ms-flex: 1 1 auto;
    flex: 1 1 auto;
    min-width: unset;
    min-height: 100%;
    max-width: 1024
}
```
Is used for?

The CSS isn't annotated so I have no clue where to look. been taking a peek here and there but haven't found elements using the classes, I might just be dumb though.

Would be appreciated if you share how you keep things organized without annotations everywhere, can help me and others contribute more.

**Comment by ockaj** [comment]
Hi class .contentColumn-1C7as6 is part of the settings page. Because Alexis did not supply any annotations, it is hard to determine which class belongs to which. For me, Google is the best choice for determining which CSS class is located where.  image

**Comment by ockaj** [comment]
To address your initial question, I just use the provided DevTools and Visual Studio Code.

**Pull request merged**
